version: "3.8"

services: 
    dbmysql:
        image: mysql:5.7
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: waproject
            MYSQL_USER: test
            MYSQL_PASSWORD: test
        restart: always
        ports: ['3306:3306']
        networks:
          - app-tier        
    api:
        build:
            context: backend
            dockerfile: Dockerfile
        container_name: nodejs
        ports: ['3002:3002']
        depends_on: 
          - dbmysql
        volumes:
          - './backend:/var/www'
          - /backend/node_modules
        networks:
          - app-tier          
    react-app:      
        stdin_open: true  
        container_name: react-app        
        environment:
            CHOKIDAR_USEPOLLING: "true"
        build:
          context: frontend
          dockerfile: Dockerfile
        ports: ['3000:3000']
        depends_on: 
          - api
        volumes:
          - './frontend:/usr/app'
          - '/frontend/node_modules'
        networks:
          - app-tier        
        
networks:
  app-tier:
    driver: bridge
